# Copyright (C) 2019-2021 Julian Valentin, LTeX Development Community
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Label Commenter"

on:
  issues:
    types:
      - "labeled"
      - "unlabeled"
  pull_request_target:
    types:
      - "labeled"
      - "unlabeled"

jobs:
  comment:
    name: "Label Commenter Job"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
          ref: "develop"

      - name: "Run Label Commenter"
        uses: "peaceiris/actions-label-commenter@v1.10.0"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          config_file: ".github/label-commenter-config.yml"
